# Used by cryptogen wto create cryptographic identities for these nodes
# Here we define one orderer organisation with 5 orderer nodes, and 2 peer organisations with 2 peers each (totalling 4 peers).
# Does not mean that all these nodes have to be created/used in the network.
# Creation of crypto material is done with cryptogen, used in network.sh

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - localhost
      - Hostname: orderer2
        SANS:
          - localhost
      - Hostname: orderer3
        SANS:
          - localhost
      - Hostname: orderer4
        SANS:
          - localhost
      - Hostname: orderer5
        SANS:
          - localhost

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true

    Template:
      Count: 4
      SANS:
        - 127.0.0.1
        - localhost
    Users:
      Count: 1

#  - Name: Org2
#    Domain: org2.example.com
#    EnableNodeOUs: true
#    Template:
#      Count: 2
#      SANS:
#        - 127.0.0.1
#        - localhost
#    Users:
#      Count: 1


