networks:
  fabric-network:
    driver: bridge
    external: true
services:
  caliper:
    networks:
      - fabric-network
    container_name: caliper
    image: hyperledger/caliper:0.6.0
    command: launch manager
    environment:
      - CALIPER_BIND_SUT=fabric:fabric-gateway
      - CALIPER_BENCHCONFIG=/hlf/hyperledgernetwork/caliper/benchmarks/config.yaml
      - CALIPER_NETWORKCONFIG=/hlf/hyperledgernetwork/caliper/networks/network-config.yaml
      - npm_config_strict_ssl=false # This is not secure.
      - CALIPER_LOGLEVEL=debug
    volumes:
      - ./:/hlf/hyperledgernetwork
#      - ./caliper:/hyperledger/caliper/workspace
#      - ./certbundle:/usr/local/share/ca-certificates/certbundle.crt
#      - ./crypto-config:/hyperledger/caliper/crypto-config

