networks:
  hyperledgernetwork_fabric-network:
    driver: bridge
    external: true
services:
  caliper:
    networks:
      - hyperledgernetwork_fabric-network
    container_name: caliper
    image: hyperledger/caliper:0.6.0
    command: launch manager unbind
    environment:
      - CALIPER_BIND_SUT=fabric:2.2
      - CALIPER_BENCHCONFIG=benchmarks/config.yaml
      - CALIPER_NETWORKCONFIG=networks/network-config.yaml
      - npm_config_strict_ssl=false # This is not secure.
      - CALIPER_LOGLEVEL=debug
    volumes:
      - ./caliper:/hyperledger/caliper/workspace
      - ./certbundle:/usr/local/share/ca-certificates/certbundle.crt
      - ./crypto-config:/hyperledger/caliper/crypto-config

