global:
  scrape_interval: 15s  # Collect metrics every 15 seconds
  evaluation_interval: 15s  # Evaluate alerting rules every 15 seconds

scrape_configs:
  - job_name: 'fabric-peers'
    static_configs:
      - targets:
          - 'peer0.org1.example.com:9443'
          - 'peer1.org1.example.com:9443'

  - job_name: 'fabric-orderers'
    static_configs:
      - targets:
          - 'orderer.example.com:9443'

