name: TestFabricNetwork
version: "2.0.0"
mutual-tls: true

caliper:
  blockchain: fabric
  sutOptions:
    gateway-enabled: false
    gateway: false
#  command:
#    start: network.sh x


# -----------------------------
# Channel Configuration
# -----------------------------
channels:
  mychannel:
    created: true
    contracts:
    - id: mychaincode

#    orderers:
#      - orderer.example.com
#      - orderer2.example.com
#      - orderer3.example.com
#      - orderer4.example.com
#      - orderer5.example.com
#    peers:
#      peer0.org1.example.com:
#        eventSource: true
#      peer1.org1.example.com:
#        eventSource: false
#      peer0.org2.example.com:
#        eventSource: true
#      peer1.org2.example.com:
#        eventSource: false

# -----------------------------
# Clients (Identities)
# -----------------------------
#clients:
#  Admin.org1.example.com:
#    client:
#      organization: Org1
      #credentialStore:
      #  path: /tmp/hfc-kvs/org1
#      credentials:
#        certificate: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
#        privateKey: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
#      clientPrivateKey:
#        path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
#      clientSignedCert:
#        path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

#  Admin.org2.example.com:
#    client:
#      organization: Org2
#      #credentialStore:
      #  path: /tmp/hfc-kvs/org2
#      clientPrivateKey:
#        path: /hyperledger/caliper/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk
#      clientSignedCert:
#        path: /hyperledger/caliper/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem

# -----------------------------
# Organization Configuration
# -----------------------------
organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'admin.org1.example.com'
        admin: true
        clientPrivateKey:
          path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
        clientSignedCert:
          path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
    connectionProfile:
      path: './connection-profile.yaml'
      discover: true
 #   peers:
 #     - endpoint: peer0.org1.example.com:7051
 #       grpcOptions:
 #         ssl-target-name-override: peer0.org1.example.com
 #         grpc.keepalive_time_ms: 600000
 #       tlsCACerts:
 #         path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
 #     - endpoint: peer1.org1.example.com:7054
 #       grpcOptions:
 #         ssl-target-name-override: peer1.org1.example.com
 #         grpc.keepalive_time_ms: 600000
 #       tlsCACerts:
 #         path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt


# -----------------------------
orderers:
  orderer.example.com:
    url: grpcs://orderer.example.com:7049
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: /hyperledger/caliper/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt

  orderer2.example.com:
    url: grpcs://orderer2.example.com:7054
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
    tlsCACerts:
      path: /hyperledger/caliper/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt

  orderer3.example.com:
    url: grpcs://orderer3.example.com:7059
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
    tlsCACerts:
      path: /hyperledger/caliper/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/ca.crt

  orderer4.example.com:
    url: grpcs://orderer4.example.com:7064
    grpcOptions:
      ssl-target-name-override: orderer4.example.com
    tlsCACerts:
      path: /hyperledger/caliper/crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/ca.crt

  orderer5.example.com:
    url: grpcs://orderer5.example.com:7069
    grpcOptions:
      ssl-target-name-override: orderer5.example.com
    tlsCACerts:
      path: /hyperledger/caliper/crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/ca.crt

# -----------------------------
# Peer Nodes
# -----------------------------
#peers:
#  peer0.org1.example.com:
#    url: grpcs://peer0.org1.example.com:11051
#    grpcOptions:
#      ssl-target-name-override: peer0.org1.example.com
#    tlsCACerts:
#      path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt

#  peer1.org1.example.com:
#    url: grpcs://peer1.org1.example.com:11054
#    grpcOptions:
#      ssl-target-name-override: peer1.org1.example.com
#    tlsCACerts:
#      path: /hyperledger/caliper/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt

#  peer0.org2.example.com:
#    url: grpcs://peer0.org2.example.com:13051
#    grpcOptions:
#      ssl-target-name-override: peer0.org2.example.com
#    tlsCACerts:
#      path: /hyperledger/caliper/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt

#  peer1.org2.example.com:
#    url: grpcs://peer1.org2.example.com:13054
#    grpcOptions:
#      ssl-target-name-override: peer1.org2.example.com
#    tlsCACerts:
#      path: /hyperledger/caliper/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/ca.crt

# -----------------------------
# Certificate Authorities (Optional)
# -----------------------------
#certificateAuthorities:
#  ca.org1.example.com:
#    url: https://ca.org1.example.com:7054
#    httpOptions:
#      verify: false
#    tlsCACerts:
#      path: ./crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem

#  ca.org2.example.com:
#    url: https://ca.org2.example.com:8054
#    httpOptions:
#      verify: false
#    tlsCACerts:
#      path: ./crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem

