name: TestFabricNetwork
version: "2.0.0"

caliper:
  blockchain: fabric


# -----------------------------
# Channel Configuration
# -----------------------------
channels:
  - channelName: mychannel
    contracts:
    - id: mychaincode
# -----------------------------
# Organization Configuration
# -----------------------------
organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'User1'
        admin: true
        clientPrivateKey:
          path: '../crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
    connectionProfile:
      path: './connection-org1.yaml'

  - mspid: Org2MSP
    identities:
      certificates:
      - name: 'User1'
        admin: true
        clientPrivateKey:
          path: '../crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem'
    connectionProfile:
      path: './connection-org2.yaml'

# -----------------------------
